# Generated by Django 5.1.7 on 2025-04-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0004_alter_mentorados_token_disponibilidadehorarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.disponibilidadedehorarios'),
        ),
        migrations.DeleteModel(
            name='DisponibilidadeHorarios',
        ),
    ]
